Use `rx.PyDiGraph` for `ConversionGraph`
qBraid/qBraid pull request #639
Opened 2024-05-30 07:56 UTC by king-p3nguin

# Changes

## Details or comments
- Resolve #618

## Before You Merge

Please review the checklist below and mark items with an `x` in the brackets that apply. Remember, it's perfectly fine
to submit a draft pull request if you're still working through some items on the checklist. We're here to help!

### General

- [ ] I have read `CONTRIBUTING.md`.
- [ ] All new code includes corresponding unit tests and satisfies codecov.
- [ ] API Reference docstrings and/or User Guide have been updated to account for new features.
- [ ] All integration tests, including remote tests, are passing.

2024-05-30 14:22 UTC, ryanhill1 requested changes
Thanks for the draft PR!

**Logistics**: Please leave a comment on issue #618; this enables me to assign you to the issue. The Unitary Fund uses these assignments to track which participants resolve issues and to distribute bounties accordingly.

**Code**: These updates look great so far! Whenever you feel your code is ready, let me know and I can run the test workflows.

2024-05-30 14:22 UTC, ryanhill1 commented on qbraid/transpiler/graph.py
> +            return rx.has_path(self, self._node_str_to_id[source], self._node_str_to_id[target])
```suggestion
        return rx.has_path(self, self._node_str_to_id[source], self._node_str_to_id[target])
```

2024-05-30 22:16 UTC, king-p3nguin commented
Thank you for the comment! I finally managed to pass all the tests, and it is ready for review.

2024-05-31 01:37 UTC, ryanhill1 approved these changes
Great work on this PR! Really impressed at how you worked through that pytket bug and used `DecomposeBoxes` to patch `harmony_transform()`, and how you identified the mismatch in preferred conversion path between networkx and rustworkx. We will soon be looking to incorporate weighted edges based on the accuracy and breadth / coverage of our supported conversions, so that update will hopefully eliminate that issue in the future.

I've reviewed the rest of your code and it's a rare moment where I don't have any requested changes! It's very well written, so once again, awesome job.

Side note: it looks like the AWS credentials stored in our github secrets expired at the *perfect* time. So sorry about those commits I made to your branch to patch the remote tests. They weren't to do with your code, just trying to work around the auth issues as quickly as possible.

That all being said, if there are any other Unitary Hack issues you're interested in tackling, either in this repo or qBraid-QIR, bountied or not, have at it! Turn around time on reviewing and merging PRs will be especially fast this week.

2024-05-31 01:39 UTC, merged