Azure Quantum V5
qBraid/qBraid pull request #723
Opened 2024-07-26 21:06 UTC by pranetksharma

# Changes
Implemented entire Azure Quantum refactoring to account for the new credential verification system.

## PR Checklist

- [x] I have read `CONTRIBUTING.md`.
- [x] All new code includes corresponding unit tests and satisfies code coverage.
- [x] API Reference docstrings have been updated for new features and changes in functionality.
- [x] All integration tests, including remote tests, are passing.
- [x]  (Optional) My name and affiliation are added to `CITATION.cff`.

2024-07-29 19:05 UTC, ryanhill1 requested changes
1. I pushed some edits that eliminate the need for the `AzureClient` class. Please update the tests to account for this.
2. Make sure that `AzureResult.measurements()` correctly returns a `np.ndarray`, and that `AzureResult.measurement_counts()` returns a dictionary of histogram data that can be plotted with `qbraid.visualization.plot_histogram()`and `qbraid.visualization.plot_distribution()`. See [docs](https://docs.qbraid.com/sdk/user-guide/visualization#plot-experimental-results).
3. `azure.quantum.Job.get_results()` is not guaranteed to return a dictionary. If there are errors decoding the data, it will return the raw payload. So let's make sure that we handle that case accordingly, e.g. by raising an exception.

2024-07-31 00:07 UTC, ryanhill1 reviewed
@pranetksharma Did you have a chance to try to submit any actual jobs? When I tried to submit an OpenQASM program to `quantinuum.sim.h1-1sc` I got 

```
ValueError: Connection string is either blank or malformed.
```

Did that happen for you?

2024-07-31 00:08 UTC, pranetksharma commented
Hmm, this may be a credential issue. Let me look into it and get back to
you!

On Tue, Jul 30, 2024 at 7:07 PM Ryan Hill ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> @pranetksharma <https://github.com/pranetksharma> Did you have a chance
> to try to submit any actual jobs? When I tried to submit an OpenQASM
> program to quantinuum.sim.h1-1sc I got
>
> ValueError: Connection string is either blank or malformed.
>
> Did that happen for you?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/qBraid/qBraid/pull/723#pullrequestreview-2208912514>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKVHYTNGURPUITP6PETQQXLZPATE3AVCNFSM6AAAAABLRFWPE2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMBYHEYTENJRGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-02 17:44 UTC, ryanhill1 submitted a review, later dismissed

2024-09-02 17:59 UTC, ryanhill1 approved these changes

2024-09-02 18:14 UTC, merged