Improve support for gates in `qasm2_to_ionq` conversion
qBraid/qBraid pull request #771
Opened 2024-10-02 07:30 UTC by TheGupta2012

## Summary of changes
- Update the `qasm2_to_ionq` conversion to include full registers being applied as quantum gate arguments 
- Moreover, the number of qubits used in gate application is not reflective of the number of qubits on which a gate acts on. Eg. `h q[0], q[1];` means `h` is being applied on 2 qubits but is itself a 1-qubit gate. Updated the logic to identify this based on gate name instead of actual qubit arguments.
- Some other updates for representing the bits of qasm programs for easier handling

2024-10-02 13:28 UTC, ryanhill1 requested changes
Looks great! Can you just add a quick update to the `CHANGELOG.md`

2024-10-02 22:34 UTC, ryanhill1 reviewed
This reminds me of similar logic we have implemented here:

https://github.com/qBraid/qBraid/blob/96cde2676ec1cb5c53519b546172d0912de88148/qbraid/passes/qasm3/compat.py#L78-L123

Do you think that we could re-use or further generalize the `replace_gate_name()` function to help minimize redundancy?

2024-10-03 17:22 UTC, TheGupta2012 commented
Well, in the ionq method we are creating a new representation i.e. the ionq json type and _not replacing the gate name in the qasm string_. 

Besides that, if we were to use the `replace_gate_name` method, it would have to be iterated over each gate key-value pair, which in turn would search through whole qasm string for each replacement ( amounting to an additional complexity of `O(|N|.|s|)` for `|N|` kv pairs and `|s|` length qasm string ). At the end, we do not need to process the updated qasm further so I feel the current approach would be a better fit for the ionq conversion.

2024-10-03 23:21 UTC, ryanhill1 approved these changes

2024-10-03 23:22 UTC, merged